### ISSUE TITLE
Prompt for desire on having the software or not

### ISSUE THREAD

**Issue by andre-ferreira-qlik** [QlikSenseStudios/Qlik-Development-Enviroment#11]
Feature request - Prompt user if they would want to download and install the software rather that being eager and doing it
From Matt

**Comment by andre-ferreira-qlik** [comment]
se

**Comment by andre-ferreira-qlik** [comment]
Sebastian had the same requirement.

**Comment by sebastianservat** [comment]
@mwbulmer @andre-ferreira-qlik Tell me what you think:

https://github.com/QlikSenseStudios/Qlik-Development-Enviroment/pull/20

**Comment by andre-ferreira-qlik** [comment]
Loved it @sebastianservat, thank you for looking at that
